export const UPDATE_SUMMARY = 'UPADTE_SUMMARY';
export const UPDATE_GLOBAL_SUMMARY = 'UPDATE_GLOABL_SUMMARY';
export const UPDATE_COUNTRIES_SUMMARY = 'UPDATE_COUNTRIES_SUMMARY';
export const UPDATE_COUNTRY_PER_DAY = 'UPDATE_COUNTRY_PER_DAY';
export const UPDATE_COUNTRIES = 'UPDATE_COUNTRIES';
export const UPDATE_SELECTED_COUNTRY = 'UPDATE_SELECTED_COUNTRY';
