export const UPDATE_SUMMARY = 'UPADTE_SUMMARY';
export const UPDATE_GLOBAL_SUMMARY = 'UPDATE_GLOABL_SUMMARY';
export const UPDATE_COUNTRIES_SUMMARY = 'UPDATE_COUNTRIES_SUMMARY';
export const UPDATE_COUNTRIES_PER_DAY = 'UPDATE_COUNTRIES_PER_DAY';
